export type Locale = 'en' | 'de';
export type ThemePreference = 'system' | 'light' | 'dark';

export const translations = {
	en: {
		appTitle: 'Recipe rotation and shopping list',
		databaseSetupNeeded: 'Database setup needed',
		databaseSetupHelp: 'Apply the D1 migration and bind the database as',
		beforeUsingApp: 'before using the app.',
		generatePlan: 'Generate plan',
		startDate: 'Start date',
		cookedFoodDays: 'Cooked-food days',
		people: 'People',
		generateDraft: 'Generate draft',
		latestPlan: 'Latest plan',
		cookedFoodDaysFor: 'cooked-food days for',
		peopleStarting: 'people, starting',
		day: 'Day',
		daySingular: 'day',
		dayPlural: 'days',
		ingredientsMultiplier: 'ingredients',
		acceptPlan: 'Accept plan and rotate recipes',
		noPlan: 'No plan generated yet.',
		addRecipe: 'Add recipe',
		name: 'Name',
		baseServings: 'Base servings',
		defaultDays: 'Default days',
		description: 'Description',
		instructions: 'Instructions',
		ingredients: 'Ingredients',
		recipeNamePlaceholder: 'Pasta with tomato sauce',
		descriptionPlaceholder: 'Quick weekday dinner',
		instructionsPlaceholder: 'Cook, combine, season.',
		ingredientsPlaceholder: 'One per line: name | quantity | unit | category | note\nPasta | 200 | g | Dry goods |\nTomatoes | 1 | can | Canned | chopped',
		saveRecipe: 'Save recipe',
		recipes: 'Recipes',
		noDescription: 'No description yet.',
		baseServingsUsually: 'base servings, usually',
		delete: 'Delete',
		noRecipes: 'No recipes yet.',
		shoppingList: 'Shopping list',
		generatePlanForShopping: 'Generate a plan to see the shopping list.',
		language: 'Language',
		english: 'English',
		german: 'German',
		theme: 'Theme',
		system: 'System',
		light: 'Light',
		dark: 'Dark',
	},
	de: {
		appTitle: 'Rezeptrotation und Einkaufsliste',
		databaseSetupNeeded: 'Datenbankeinrichtung erforderlich',
		databaseSetupHelp: 'Wende die D1-Migration an und binde die Datenbank als',
		beforeUsingApp: 'bevor du die App verwendest.',
		generatePlan: 'Plan erstellen',
		startDate: 'Startdatum',
		cookedFoodDays: 'Tage mit gekochtem Essen',
		people: 'Personen',
		generateDraft: 'Entwurf erstellen',
		latestPlan: 'Aktueller Plan',
		cookedFoodDaysFor: 'Tage mit gekochtem Essen fuer',
		peopleStarting: 'Personen, ab',
		day: 'Tag',
		daySingular: 'Tag',
		dayPlural: 'Tage',
		ingredientsMultiplier: 'Zutaten',
		acceptPlan: 'Plan annehmen und Rezepte rotieren',
		noPlan: 'Noch kein Plan erstellt.',
		addRecipe: 'Rezept hinzufuegen',
		name: 'Name',
		baseServings: 'Basisportionen',
		defaultDays: 'Standardtage',
		description: 'Beschreibung',
		instructions: 'Zubereitung',
		ingredients: 'Zutaten',
		recipeNamePlaceholder: 'Pasta mit Tomatensauce',
		descriptionPlaceholder: 'Schnelles Abendessen unter der Woche',
		instructionsPlaceholder: 'Kochen, vermengen, abschmecken.',
		ingredientsPlaceholder: 'Eine Zeile pro Zutat: Name | Menge | Einheit | Kategorie | Notiz\nPasta | 200 | g | Trockenware |\nTomaten | 1 | Dose | Konserven | gehackt',
		saveRecipe: 'Rezept speichern',
		recipes: 'Rezepte',
		noDescription: 'Noch keine Beschreibung.',
		baseServingsUsually: 'Basisportionen, normalerweise',
		delete: 'Loeschen',
		noRecipes: 'Noch keine Rezepte.',
		shoppingList: 'Einkaufsliste',
		generatePlanForShopping: 'Erstelle einen Plan, um die Einkaufsliste zu sehen.',
		language: 'Sprache',
		english: 'Englisch',
		german: 'Deutsch',
		theme: 'Design',
		system: 'System',
		light: 'Hell',
		dark: 'Dunkel',
	},
} as const;

export type TranslationKey = keyof typeof translations.en;

export function detectLocale(acceptLanguage: string | null): Locale {
	return acceptLanguage?.toLowerCase().startsWith('de') ? 'de' : 'en';
}

