export type Locale = 'en' | 'de';
export type ThemePreference = 'system' | 'light' | 'dark';

export const LOCALE_COOKIE = 'foodie.locale';

export const INGREDIENT_CATEGORIES = ['Produce', 'Dairy', 'Meat', 'Dry goods', 'Spices', 'Canned', 'Frozen', 'Other'] as const;

export const translations = {
	en: {
		appTitle: 'Recipe rotation and shopping list',
		databaseSetupNeeded: 'Database setup needed',
		databaseSetupHelp: 'Apply the D1 migration and bind the database as',
		beforeUsingApp: 'before using the app.',
		generatePlan: 'Generate plan',
		generateNewPlan: 'Generate a new plan',
		startDate: 'Start date',
		cookedFoodDays: 'Cooked-food days',
		people: 'People',
		generateDraft: 'Generate draft',
		latestPlan: 'Latest plan',
		cookedFoodDaysFor: 'cooked-food days for',
		peopleStarting: 'people, starting',
		day: 'Day',
		daySingular: 'day',
		dayPlural: 'days',
		ingredientsMultiplier: 'ingredients',
		acceptPlan: 'Accept plan and rotate recipes',
		adjustPlan: 'Adjust plan',
		regeneratePlan: 'Regenerate draft',
		draftBadge: 'Draft',
		acceptedBadge: 'Accepted',
		noPlan: 'No plan yet',
		planEmptyHelp: 'Generate a draft plan to fill your week with recipes that have waited longest.',
		addRecipesFirst: 'Add a recipe before generating a plan.',
		noDraftPlan: 'No draft plan to adjust',
		noDraftPlanHelp: 'Generate a draft plan first, then adjust days or swap recipes here.',
		replaceWith: 'Replace with',
		replace: 'Replace',
		update: 'Update',
		days: 'Days',
		recipes: 'Recipes',
		newRecipe: 'New recipe',
		editRecipe: 'Edit recipe',
		searchRecipes: 'Search recipes',
		noSearchResults: 'No recipes match your search.',
		noRecipes: 'No recipes yet',
		recipesEmptyHelp: 'Add your first recipe to start planning meals.',
		lastCooked: 'Last cooked',
		neverCooked: 'Never cooked',
		addRecipe: 'Add recipe',
		name: 'Name',
		baseServings: 'Base servings',
		defaultDays: 'Default days',
		description: 'Description',
		instructions: 'Instructions',
		ingredients: 'Ingredients',
		ingredient: 'Ingredient',
		addIngredient: 'Add ingredient',
		remove: 'Remove',
		quantity: 'Quantity',
		unit: 'Unit',
		category: 'Category',
		note: 'Note',
		recipeNamePlaceholder: 'Pasta with tomato sauce',
		descriptionPlaceholder: 'Quick weekday dinner',
		instructionsPlaceholder: 'Cook, combine, season.',
		ingredientNamePlaceholder: 'Pasta',
		notePlaceholder: 'optional',
		saveRecipe: 'Save recipe',
		saveChanges: 'Save changes',
		deleteRecipe: 'Delete recipe',
		delete: 'Delete',
		back: 'Back',
		noDescription: 'No description yet.',
		recipeNotFound: 'Recipe not found.',
		shoppingList: 'Shopping list',
		generatePlanForShopping: 'Generate a plan to see the shopping list.',
		itemsChecked: 'checked',
		categoryProduce: 'Produce',
		categoryDairy: 'Dairy',
		categoryMeat: 'Meat',
		categoryDryGoods: 'Dry goods',
		categorySpices: 'Spices',
		categoryCanned: 'Canned',
		categoryFrozen: 'Frozen',
		categoryOther: 'Other',
		aiSection: 'AI assistant',
		aiSectionHelp: 'Add your own API key to generate and edit recipes with an AI model. The key is stored in the app database.',
		aiProvider: 'Provider',
		aiModel: 'Model',
		aiApiKey: 'API key',
		aiApiKeyKeepHelp: 'Leave empty to keep the saved key.',
		aiConfigured: 'Configured',
		aiNotConfigured: 'Not configured',
		aiSave: 'Save AI settings',
		aiRemoveKey: 'Remove key',
		aiSettingsHint: 'Add your AI API key in Settings to generate recipes.',
		generateWithAi: 'Generate with AI',
		aiPromptPlaceholder: 'e.g. A quick vegetarian pasta for weekdays',
		aiGenerateButton: 'Generate recipe',
		editWithAi: 'Edit with AI',
		aiEditPlaceholder: 'e.g. Make it vegetarian and scale to 4 servings',
		aiApplyButton: 'Apply change',
		aiErrorTitle: 'AI request failed',
		language: 'Language',
		english: 'English',
		german: 'German',
		theme: 'Theme',
		system: 'System',
		light: 'Light',
		dark: 'Dark',
		planNav: 'Plan',
		recipesNav: 'Recipes',
		shoppingNav: 'Shopping',
		settingsNav: 'Settings',
		signInTitle: 'Sign in',
		signInHelp: 'Sign in with Google or Apple to manage your recipes.',
		continueWithGoogle: 'Continue with Google',
		continueWithApple: 'Continue with Apple',
		workosMissing: 'WorkOS is not configured.',
		workosMissingHelp: 'Set WORKOS_API_KEY, WORKOS_CLIENT_ID, and WORKOS_COOKIE_PASSWORD as Cloudflare Worker secrets.',
		signOut: 'Sign out',
	},
	de: {
		appTitle: 'Rezeptrotation und Einkaufsliste',
		databaseSetupNeeded: 'Datenbankeinrichtung erforderlich',
		databaseSetupHelp: 'Wende die D1-Migration an und binde die Datenbank als',
		beforeUsingApp: 'bevor du die App verwendest.',
		generatePlan: 'Plan erstellen',
		generateNewPlan: 'Neuen Plan erstellen',
		startDate: 'Startdatum',
		cookedFoodDays: 'Tage mit gekochtem Essen',
		people: 'Personen',
		generateDraft: 'Entwurf erstellen',
		latestPlan: 'Aktueller Plan',
		cookedFoodDaysFor: 'Tage mit gekochtem Essen für',
		peopleStarting: 'Personen, ab',
		day: 'Tag',
		daySingular: 'Tag',
		dayPlural: 'Tage',
		ingredientsMultiplier: 'Zutaten',
		acceptPlan: 'Plan annehmen und Rezepte rotieren',
		adjustPlan: 'Plan anpassen',
		regeneratePlan: 'Entwurf neu erstellen',
		draftBadge: 'Entwurf',
		acceptedBadge: 'Angenommen',
		noPlan: 'Noch kein Plan',
		planEmptyHelp: 'Erstelle einen Planentwurf mit den Rezepten, die am längsten warten.',
		addRecipesFirst: 'Füge zuerst ein Rezept hinzu, bevor du einen Plan erstellst.',
		noDraftPlan: 'Kein Entwurf zum Anpassen',
		noDraftPlanHelp: 'Erstelle zuerst einen Planentwurf, dann kannst du hier Tage ändern oder Rezepte tauschen.',
		replaceWith: 'Ersetzen durch',
		replace: 'Ersetzen',
		update: 'Aktualisieren',
		days: 'Tage',
		recipes: 'Rezepte',
		newRecipe: 'Neues Rezept',
		editRecipe: 'Rezept bearbeiten',
		searchRecipes: 'Rezepte suchen',
		noSearchResults: 'Keine Rezepte gefunden.',
		noRecipes: 'Noch keine Rezepte',
		recipesEmptyHelp: 'Füge dein erstes Rezept hinzu, um mit der Planung zu starten.',
		lastCooked: 'Zuletzt gekocht',
		neverCooked: 'Noch nie gekocht',
		addRecipe: 'Rezept hinzufügen',
		name: 'Name',
		baseServings: 'Basisportionen',
		defaultDays: 'Standardtage',
		description: 'Beschreibung',
		instructions: 'Zubereitung',
		ingredients: 'Zutaten',
		ingredient: 'Zutat',
		addIngredient: 'Zutat hinzufügen',
		remove: 'Entfernen',
		quantity: 'Menge',
		unit: 'Einheit',
		category: 'Kategorie',
		note: 'Notiz',
		recipeNamePlaceholder: 'Pasta mit Tomatensauce',
		descriptionPlaceholder: 'Schnelles Abendessen unter der Woche',
		instructionsPlaceholder: 'Kochen, vermengen, abschmecken.',
		ingredientNamePlaceholder: 'Pasta',
		notePlaceholder: 'optional',
		saveRecipe: 'Rezept speichern',
		saveChanges: 'Änderungen speichern',
		deleteRecipe: 'Rezept löschen',
		delete: 'Löschen',
		back: 'Zurück',
		noDescription: 'Noch keine Beschreibung.',
		recipeNotFound: 'Rezept nicht gefunden.',
		shoppingList: 'Einkaufsliste',
		generatePlanForShopping: 'Erstelle einen Plan, um die Einkaufsliste zu sehen.',
		itemsChecked: 'erledigt',
		categoryProduce: 'Obst & Gemüse',
		categoryDairy: 'Milchprodukte',
		categoryMeat: 'Fleisch',
		categoryDryGoods: 'Trockenware',
		categorySpices: 'Gewürze',
		categoryCanned: 'Konserven',
		categoryFrozen: 'Tiefkühl',
		categoryOther: 'Sonstiges',
		aiSection: 'KI-Assistent',
		aiSectionHelp: 'Hinterlege deinen eigenen API-Schlüssel, um Rezepte mit einem KI-Modell zu erstellen und zu bearbeiten. Der Schlüssel wird in der App-Datenbank gespeichert.',
		aiProvider: 'Anbieter',
		aiModel: 'Modell',
		aiApiKey: 'API-Schlüssel',
		aiApiKeyKeepHelp: 'Leer lassen, um den gespeicherten Schlüssel zu behalten.',
		aiConfigured: 'Eingerichtet',
		aiNotConfigured: 'Nicht eingerichtet',
		aiSave: 'KI-Einstellungen speichern',
		aiRemoveKey: 'Schlüssel entfernen',
		aiSettingsHint: 'Hinterlege deinen KI-API-Schlüssel in den Einstellungen, um Rezepte zu generieren.',
		generateWithAi: 'Mit KI erstellen',
		aiPromptPlaceholder: 'z. B. Schnelle vegetarische Pasta für unter der Woche',
		aiGenerateButton: 'Rezept erstellen',
		editWithAi: 'Mit KI bearbeiten',
		aiEditPlaceholder: 'z. B. Mach es vegetarisch und skaliere auf 4 Portionen',
		aiApplyButton: 'Änderung anwenden',
		aiErrorTitle: 'KI-Anfrage fehlgeschlagen',
		language: 'Sprache',
		english: 'Englisch',
		german: 'Deutsch',
		theme: 'Design',
		system: 'System',
		light: 'Hell',
		dark: 'Dunkel',
		planNav: 'Plan',
		recipesNav: 'Rezepte',
		shoppingNav: 'Einkauf',
		settingsNav: 'Einstellungen',
		signInTitle: 'Anmelden',
		signInHelp: 'Melde dich mit Google oder Apple an, um deine Rezepte zu verwalten.',
		continueWithGoogle: 'Mit Google fortfahren',
		continueWithApple: 'Mit Apple fortfahren',
		workosMissing: 'WorkOS ist nicht konfiguriert.',
		workosMissingHelp: 'Setze WORKOS_API_KEY, WORKOS_CLIENT_ID und WORKOS_COOKIE_PASSWORD als Cloudflare Worker Secrets.',
		signOut: 'Abmelden',
	},
} as const;

export type TranslationKey = keyof typeof translations.en;

export function detectLocale(acceptLanguage: string | null): Locale {
	return acceptLanguage?.toLowerCase().startsWith('de') ? 'de' : 'en';
}

const CATEGORY_KEYS: Record<string, TranslationKey> = {
	'produce': 'categoryProduce',
	'dairy': 'categoryDairy',
	'meat': 'categoryMeat',
	'dry goods': 'categoryDryGoods',
	'spices': 'categorySpices',
	'canned': 'categoryCanned',
	'frozen': 'categoryFrozen',
	'other': 'categoryOther',
};

export function translateCategory(locale: Locale, category: string): string {
	const key = CATEGORY_KEYS[category.trim().toLowerCase()];
	return key ? translations[locale][key] : category;
}
