onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
minimumReleaseAgeExclude:
  - '@cloudflare/workerd-darwin-64@1.20260611.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260611.1'
  - '@cloudflare/workerd-linux-64@1.20260611.1'
  - '@cloudflare/workerd-linux-arm64@1.20260611.1'
  - '@cloudflare/workerd-windows-64@1.20260611.1'
  - '@cloudflare/workers-types@4.20260611.1'
  - miniflare@4.20260611.0
  - workerd@1.20260611.1
  - wrangler@4.100.0
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
